# Generated by Django 5.1.1 on 2024-09-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
    ]
