# Generated by Django 5.1.1 on 2024-09-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_question', '0006_alter_answer_answer_text'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='chapter',
            table=None,
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
