# Generated by Django 5.1.1 on 2024-09-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_question', '0008_chapter_created_at_alter_answer_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
